version: "3.8"

services:
  app:
    build: .
    container_name: perfume_app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: perfume_db
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "${DB_USER}",
          "-p${DB_PASS}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
